# Funding / sponsorship links shown on the repo's "Sponsor" button.
# Uncomment and fill in once the corresponding account is set up.
# github: [UltimaPhoenix]
# custom: ["https://github.com/UltimaPhoenix/dev-coach#license"]
