sonar.projectKey=UltimaPhoenix_dev-coach
sonar.organization=ultimaphoenix

sonar.projectName=devcoach
sonar.projectVersion=0.3.6

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
